### ISSUE TITLE
text_DeepL: AchievementText_en-CAB: Verify Name

### ISSUE THREAD

**Issue by Cristalim** [TailsKitsune/Eiyuden-Chronicles_Retranslated#15]
Please check the name of this file as the content matches "AchievementTalkText_ja-CAB.txt". 

(Internally, the file is identified as "AchievementTalkText_en". 
The "AchievementText_ja-CAB" exists, however its contents do not match this file.)

Thank you!

**Comment by TailsKitsune** [comment]
Changed the name of the file
